### ISSUE TITLE
Add an RSS Feed Reader

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-cli-apps#105]

**Comment by remembertoremind** [comment]
Hi :) I guess you need help? So.. I installed Arch Linux as my first Linux dist ever. So I'm really learning a lot of new stuff and I really like your list.

RSS reader? I found Newsbeuter, and I really like it. Combine it with Podbeuter and mplayer = <3

**Comment by aharris88** [comment]
That looks great! Do you want to put in a pull request?

**Comment by remembertoremind** [comment]
I would love to but I have no idea of how :) Or.. I would have to learn how to first.

**Comment by aharris88** [comment]
Cool. This would be a great first project to contribute to. It's as easy as [going to the file you want to change](https://github.com/aharris88/awesome-cli-apps/blob/master/README.md) and clicking the pencil icon.

**Comment by remembertoremind** [comment]
Okay :) I took the leap and have made my first change. I hope I haven't messed anything up. Thank you for the encouragement.
