### ISSUE TITLE
Make sure each cli app has an open source license

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-cli-apps#106]
If a cli app doesn't have a cli license, open an issue, asking them to add a license.

- [x] [rename-cli](https://github.com/aharris88/awesome-cli-apps/pull/99)
- [x] [open-pip-cli](https://github.com/albinekb/open-pip-cli/issues/9)
- [x] [caniuse-cmd](https://github.com/sgentle/caniuse-cmd/issues/17)
- [ ] [AutoScreenshotUploader](https://github.com/yask123/AutoScreenshotUploader/issues/4)
- [ ] [geeknote](https://github.com/VitaliyRodnenko/geeknote/issues/244)
- [x] [j](https://github.com/rupa/j/issues/1)

**Comment by capaldo** [comment]
@jneidel Same here. Looking to close this and we can re-open an issue with a full list if we decide to revisit/tackle this.
