### ISSUE TITLE
Add more related awesome lists to "Other Awesome Lists" section

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-cli-apps#108]

**Comment by jneidel** [comment]
How about:
- https://github.com/herrbischoff/awesome-command-line-apps#readme
- https://github.com/sindresorhus/awesome-nodejs#command-line-apps
- https://github.com/herrbischoff/awesome-macos-command-line#readme
- https://github.com/alebcay/awesome-shell#readme
- https://github.com/unixorn/awesome-zsh-plugins#readme
- https://github.com/k4m4/terminals-are-sexy#readme

*in no particular order*

**Comment by capaldo** [comment]
I'll go ahead and add the additional ones now.
