### ISSUE TITLE
Organize Categories Better

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-cli-apps#14]
I've got so many things in the Other category, that it's time to start breaking things out into better categories. Let me know if you have any ideas.

**Comment by Moshe-Immerman** [comment]
would you be open to large re-org?  e.g.  alphabetise links, re-order / re-name categories?

**Comment by sjclayton** [comment]
@jneidel @agarrharr Closing this-  Since I think it'd be easier to discuss category reorganization, the creation of new categories / subcategories on an individual basis.
