### ISSUE TITLE
Remove 'movie' from the list

### ISSUE THREAD

**Issue by bonds** [agarrharr/awesome-cli-apps#157]
According to the README, its broken and won't be fixed:

https://github.com/mayankchd/movie

**Comment by xxczaki** [comment]
I submitted a [PR](https://github.com/mayankchd/movie/pull/5) to make this module work again, but idk if the owner is still interested in it.

**Comment by agarrharr** [comment]
That would be nice. Great work! 👍

**Comment by Nikronic** [comment]
The API key no longer works. It is paid service now so it won't work again. Please remove **movie**

**Comment by sjclayton** [comment]
So should / can this be closed now, since it would appear it's been updated and is now working again..?
