### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by sdemura** [agarrharr/awesome-cli-apps#161]
NCDu - https://dev.yorhel.nl/ncdu
Glances - https://nicolargo.github.io/glances/
Ripgrep - https://github.com/BurntSushi/ripgrep
Neofetch - https://github.com/dylanaraps/neofetch

**Comment by sjclayton** [comment]
Done -- Added NCDu, Glances and ripgrep..

Also Glances is awesome, and should definitely be on this list. I use it myself! :smile:
