### ISSUE TITLE
[Suggestion] Spreadsheet Calculator - Productivity

### ISSUE THREAD

**Issue by danieldeveloper001** [agarrharr/awesome-cli-apps#166]
Hello, I would like to suggest a spreadsheet application for the productivity list.

[Spreadsheet Calculator](https://github.com/n-t-roff/sc) - A console curses based spreadsheet application.

https://en.wikipedia.org/wiki/Sc_(spreadsheet_calculator)

Regards.

**Comment by jneidel** [comment]
Hey @danieldeveloper001,
feel free to open a pull request adding `sc`, then we'll review your submission!
