### ISSUE TITLE
Add CI to verify validity of links

### ISSUE THREAD

**Issue by simeg** [agarrharr/awesome-cli-apps#185]
Having broken links sucks, and what sucks even more is manually going through all the links to check if anyone of them are dead. I propose adding CI (like Travis CI) in a separate branch/repo that is configured to run a script every 24 hours.

This script would parse out all the http links and cURL them one by one. If anyone of them respond with a `5xx` it would fail. This repo could then show a badge from that Travis build to indicate if all links are good or if anyone of them are dead.

It's scalable and doesn't require any maintenance (unless readme structure changes or etc.).

Thoughts?

**Comment by agarrharr** [comment]
I would love that. Could you submit a PR?

**Comment by simeg** [comment]
I could, but first we would need to agree on where to put it. Having a separate branch sounds tedious to me, a separate repo sounds better. What do you think? It makes sense for it to live on your account no matter the approach.

If you think a separate repo sounds ok you can create one and I'll submit a PR.

**Comment by agarrharr** [comment]
Having a separate repo seems a little odd to me. What would be tedious about a branch?

What might be even better is just having a Github bot that submits a pull request if it finds a broken link. Then this could be used for many different projects. I wonder if this exists already...

**Comment by agarrharr** [comment]
It looks like this may already be doing this for every repo on GitHub: https://github.com/evuez/github-links-checker.

**Comment by simeg** [comment]
My experience is that it's easier to accidentally merge branches that should not be merged than repos.

Yeah, a bot that does PRs that automatically removes broken links _would_ be even better. I have no experience writing bots for GitHub though but I have a script ready to go for my proposal.

That python bot looks ok, but latest issue is from 2015 so I'm guessing it's not running anymore. Or maybe I'm misunderstanding it.

**Comment by agarrharr** [comment]
Ok, cool, here it is: https://github.com/agarrharr/awesome-cli-apps-link-checker

**Comment by simeg** [comment]
Ok cool! I just updated my comment suggesting to do it in a branch, I'll leave that decision up to you :) I'm fine with whatever.

Going to bed now so just let me know what you think is best and I'll create a PR when it's done. If you go with the repo maybe it could be donw in such a way that it checks for all of your list repos? I noticed you have several.

**Comment by agarrharr** [comment]
Yeah, let's go ahead and do it in a separate repo. It would be nice to check all my list repos.

https://github.com/agarrharr/awesome-link-checker

**Comment by agarrharr** [comment]
@simeg ping! Do you still have that script ready?

**Comment by simeg** [comment]
Hey @agarrharr. Been busy lately with IRL stuff but been meaning to fix this. Will try to get it done soon.

**Comment by simeg** [comment]
Still have this on my TODO list. Been busy with IRL stuff (as you can tell from my commit history) but I intend to complete this soon. Sorry for the delay.

**Comment by sjclayton** [comment]
Closing this, since it appears to be up and running now.
