### ISSUE TITLE
add Telegram-cli

### ISSUE THREAD

**Issue by elhenro** [agarrharr/awesome-cli-apps#187]
https://github.com/vysheng/tg

**Comment by sjclayton** [comment]
Feel free to submit a pull request to have this reviewed and added to the appropriate section. :smile:

**Comment by elhenro** [comment]
@sjclayton  you could consider adding the [contributing section](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md) to the readme, so it wouldn't be necessary to repeat your PR reminder 👍
