### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-cli-apps#247]
I haven't had the time/interest to work on this lately. If anyone else is interested in working on this, let me know.

**Comment by jamesgeorge007** [comment]
@agarrharr I would like to work on this :+1:

**Comment by agarrharr** [comment]
Sounds good. I sent you an invite.

**Comment by onehungrygeek** [comment]
> I haven't had the time/interest to work on this lately. If anyone else is interested in working on this, let me know.

@agarrharr Sure, I can help maintain this :100:

**Comment by jamesgeorge007** [comment]
@agarrharr It seems that I haven't received an invitation yet :thinking:

**Comment by agarrharr** [comment]
https://github.com/agarrharr/awesome-cli-apps/invitations

**Comment by chrismullins** [comment]
Happy to help!

**Comment by guangrei** [comment]
me, i have follow/watch this repository for a long time :)

**Comment by sjclayton** [comment]
Would also love to help maintain this! :grinning:

**Comment by jneidel** [comment]
I'd be interested in helping as well!

**Comment by HumanJBooF** [comment]
I am interested if still needed!

**Comment by paulrm** [comment]
Hello @agarrharr, I will very happy to help

**Comment by capaldo** [comment]
I'm also interested in helping maintain as I'm constantly looking for new cli apps.

**Comment by nber1994** [comment]
I am very willing to participate in this project, I have always been fascinated by this！

**Comment by StewAlexanderACC** [comment]
I might be able to help, nice to know others are too

**Comment by agarrharr** [comment]
There are a lot of collaborators now. It might be time to close this issue?

**Comment by jneidel** [comment]
> There are a lot of collaborators now. It might be time to close this issue?

I think so too. We can always reopen if we feel the need for it
