### ISSUE TITLE
Add omz-hist

### ISSUE THREAD

**Issue by lfromanini** [agarrharr/awesome-cli-apps#253]
Can you please add my Zsh history plugin to your list if you think it deserves?
https://github.com/lfromanini/omz-hist

Thanks in advance!

**Comment by sjclayton** [comment]
First of all, thank you for your submission / contribution. :+1: 

I think we'll be passing on this one for now, we can't add every app to the list as it is a curated list of apps.

I encourage you to try submitting this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins).

Good luck!!
