### ISSUE TITLE
Add lsd

### ISSUE THREAD

**Issue by nighthawk9** [agarrharr/awesome-cli-apps#261]
https://github.com/Peltoche/lsd

**Comment by sjclayton** [comment]
Feel free to submit a pull request to have this added to the appropriate category! :grin:

**Comment by nighthawk9** [comment]
Will submit the pull request soon

**Comment by jneidel** [comment]
Personally it only adds something on `lsd -l`, as the permissions are colored.
Other than that, the icons just clutter your ui and the colors are almost the same as with regular ls. In total, for me, it's detracting from the overall experience.

**Comment by sjclayton** [comment]
@jneidel We can't be too personally subjective with what we think should / shouldn't be added to the list.. 

As if that were the case, in my instance at least the list would be a lot smaller than it is... :stuck_out_tongue:
