### ISSUE TITLE
Create Pull Request Template

### ISSUE THREAD

**Issue by sjclayton** [agarrharr/awesome-cli-apps#264]

**Comment by jneidel** [comment]
I was thinking the same thing. Too many PR without any or too little context.

My suggestion:

```md
<!--
Thank you for your pull request. Please provide a short description of the cli
and a link to it's repository or homepage. 

Make sure the PR adheres to the contribution guidelines:
https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md
-->
```

Based on [nodes template](https://raw.githubusercontent.com/nodejs/node/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by sjclayton** [comment]
I was thinking of something a bit more in-depth, but not sure exactly what that would entail entirely.

At any rate whatever we do come up with needs to have YAML front matter that automatically adds the label **needs review** to any new pull request.. as it will assist with identifying new PR's faster, as well as in trying to establish a new system based on the labels **pending**, **needs review** and **on hold**... Which I believe will aid in managing all PR's as we continue to receive more.
