### ISSUE TITLE
Add JSON subcategory

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#269]
There are a few different clis that deal with handling/manipulating JSON.
We could merge them into their own subcategory. Maybe under Data Manipulation or Development.

clis:
- vj
- jq
- jp
- fx
- strip-json-comments-cli

**Comment by sjclayton** [comment]
@jneidel I agree anything related to JSON manipulation / working with JSON should go in a subcategory named **JSON** under Data Manipulation. 

Then any other non JSON related CLI apps that are Data Manipulation related can just live under the parent category for now, until we have enough of a certain type to split them.
