### ISSUE TITLE
Add Check Name subcategory

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#270]
There are 2+ clis for checking whenever a name is available. These could be grouped into their own subcategory.

I'm not too sure on the name of subcategory.

clis (havn't checked all):
- npm-name-cli
- bower-name-cli
- is-trademarked-cli (from ideas.txt)

**Comment by sjclayton** [comment]
I think we might hold off on this.. I don't think it would be feasible to add a subcategory for this... maybe if there were at least a couple more apps to go in it. I know there are already subcategories with only 2-3 apps. 

I just don't know if creating one called **Check Name** would be understood or useful right now.

**Comment by sjclayton** [comment]
@jneidel ping...

**Comment by jneidel** [comment]
Still relevant, but maybe we can find a better name for the category.

**Comment by jneidel** [comment]
Oh, it seems I missed your comment, sorry.
Let's revisit this later.
