### ISSUE TITLE
Add Speed Test subcategory

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#271]
There are 3 clis in Other, that are all related to speedtest.net. We could group these into a subcategory of Other.

clis:
- speedtest-net
- speed-test
- speedtest-cli

**Comment by sjclayton** [comment]
I was thinking about the potential to create a **Network Utilities** subcategory under **Utilities** for this... let me know what you think.

**Comment by jneidel** [comment]
Yeah, that better.

Maybe than we can add these as well:
- get-port-cli
- is-reachable-cli

**Comment by sjclayton** [comment]
I think each potential entry for the new  subcategory should be double checked to make sure it fits..

The 2 you suggested seem to be prime examples though. :grin:
