### ISSUE TITLE
What about clis that are only relevant to very few people

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#272]
The purpose of this is to start a discussion, not exclude what is not relevant to me.

I'm talking about clis like [google-wifi-status](https://github.com/joelgeorgev/google-wifi-status) or the blockchain tools of #212.
And I mean few, as in compared to 100% of people that look at this repo.

Should every suggested clis be added as long as it matches the requirements, no matter how irrelevant it may be to most people? Doesn't this bloat the repo?
What is the focus of this repo? To be all encompassing or only show the most relevant? What is relevant?
Prefer more general clis over those that are very focused?

**Example**
_figlet_: Prints big letters out of ascci characters; This cli is potentially relevant to everybody using the latin alphabet
_google-wifi-status_: displays status of your Google Wifi; This is only potentially relevant to those using google wifi

**Comment by agarrharr** [comment]
I was originally going to try to keep it focused on cli tools that are full-fledged apps, like apps that are time-trackers, evernote clients, twitter clients, email clients, rss readers, accounting apps, etc. But it has grown beyond this with utilities, data manipulation, and file/directory tools.

I generally try to not include cli tools that require some programming to use, or that are too developer focused (i.e. Angular CLI)

**Comment by nighthawk9** [comment]
I for one enjoy seeing all the command line applications regardless of the size of the user base. Finding niche applications is often quite hard if it is not well known. I go to awesome lists to find ALL the utilities related to what I'm trying accomplish or do.

**Comment by sjclayton** [comment]
Personally, for me it's mainly about quality over quantity.

I would rather focus on keeping the list as high quality as possible... which, if that were the direction we headed towards, it would probably necessitate going through the list with a fine tooth comb and potentially removing quite a few of the entries.

But again, that's just my opnion...

**Comment by jneidel** [comment]
> for me it's mainly about quality over quantity.
I feel the same way.

But how do we define quality and how does the relevance (from the beginning of this issue) factor into it?

**Comment by jneidel** [comment]
> Also more discussion is needed regarding maybe setting up some guidelines for minimum requirements for a given app being accepted to be added to the list.
> I mean ultimately I don't really think there should be _minimum requirements_ really. But we do need some sort of benchmark to go by.

What do you think of a champion system, like [tc39](https://github.com/tc39/proposals)s, where somebody takes on a app that they like.
If we could somehow involve the community, maybe through some kind of voting, that would be great as well. Maybe give an app a timeframe of a week to either find a contributor to champion it or get voted in by the community.
I would apply this to apps that are currently labeled _on hold_, i.e. those that aren't an easy merge (easy as they are relevant or have lots of stars, etc.).

**Comment by capaldo** [comment]
> > for me it's mainly about quality over quantity.
> 
> I feel the same way.
> 
> But how do we define quality and how does the relevance (from the beginning of this issue) factor into it?
> Does our own opinion factor into quality or should we be objective? What does objective mean?



> > Also more discussion is needed regarding maybe setting up some guidelines for minimum requirements for a given app being accepted to be added to the list.
> > I mean ultimately I don't really think there should be _minimum requirements_ really. But we do need some sort of benchmark to go by.
> 
> What do you think of a champion system, like [tc39](https://github.com/tc39/proposals)s, where somebody takes on a app that they like.
> If we could somehow involve the community, maybe through some kind of voting, that would be great as well. Maybe give an app a timeframe of a week to either find a contributor to champion it or get voted in by the community.
> I would apply this to apps that are currently labeled _on hold_, i.e. those that aren't an easy merge (easy as they are relevant or have lots of stars, etc.).

These are all great points. I think that if the community does not chime in, we can make that assessment ([via a poll maybe?](https://github.com/tj/gh-polls?ref=producthunt)) amongst ourselves and review just how active/useful a cli app is on a case-by-case basis.

Let me know what you guys think.

**Comment by jneidel** [comment]
Closing as the discussion served it's purpose.
