### ISSUE TITLE
Add Release subcategory

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#274]
There are a few clis related to releasing new version, which could be grouped.

- release-it
- clog
- #217 
- #82 

As **Release** under **Development**

**Comment by sjclayton** [comment]
Looks good!! :100:

**Comment by jneidel** [comment]
@sjclayton do you want me to directly implement this, or should I open a PR for every subcategory?

**Comment by sjclayton** [comment]
@jneidel I would prefer to do it through separate PR's... although I have done some reorganization directly in the past few days.
