### ISSUE TITLE
Cleanup Entertainment category

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#285]
It's the first category everybody sees and the subcategory are well organized, but the first 6 entries are too varied and could rather be split up.

### New "Movie" subcategory in "Entertainment"

Move these into their own category:

- moviemon
- movie
- #196 

### Move quote-cli

Move it into either **Just for Fun** or **Other**

### Move splash-cli

Move into **Images**

### Keep football-cli & pockyt

As they don't really fit anywhere else, but thematically fit well into **Entertainment** they should stay there for now.

**Comment by sjclayton** [comment]
@jneidel 

Yeah I agree, I think we should do something with this...

Move the first two to a **Movies** subcategory... I still haven't decided what to do with #196, if anything I think it might go under **Video** instead.

**quote-cli** should probably go under **Just for Fun**

Leave **splash-cli** for now as I am planning a new subcategory that it will fit into.

The last two can stay in **Entertainment** as they do seem like they belong there at the moment.

**Comment by jneidel** [comment]
> I still haven't decided what to do with #196, if anything I think it might go under **Video** instead.
I personally only use subtitles for movies/series. And for most other media (eg. youtube) subtitles might not be consistently available.
I feel like it fits **Movie** better than the more general **Video**.
