### ISSUE TITLE
Add link in header for "On Hold" PR's

### ISSUE THREAD

**Issue by sjclayton** [agarrharr/awesome-cli-apps#293]
I think it might be a good idea to place a link at the top of the page somewhere that allows people to checkout apps that haven't made the list (ie. that currently have the label **On Hold**).

My thinking is that maybe it'll get those apps some love if they are actually **_awesome_**, and help us down the road in deciding whether or not they should be added at a later date.

What does everyone else think?

**Comment by jneidel** [comment]
Seems like a good idea!

[Potential link](https://github.com/agarrharr/awesome-cli-apps/pulls?q=is%3Apr+is%3Aopen+sort%3Acreated-asc+label%3A"on+hold")

- Sorts from old to new

**Comment by sjclayton** [comment]
Yeah I like it... I think I'm going to go ahead and do it...

Also more discussion is needed as per #272 regarding maybe setting up some guidelines for minimum requirements for a given app being accepted to be added to the list.
