### ISSUE TITLE
Clean out open PRs?

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#320]
I think we should remove all open pull requests that are on hold.

Nothing is happening there (no :+1: on any), they are awfully formatted and clutter the PR section.
I think just by having them we are discouraging people from adding new PRs.

And having them they there just show indecisiveness on our (maintainers) part, as putting these apps on hold is clearly a rejection but were not rejecting them outright by closing the PR.

I think a better approach would be to close all that are `on hold`, remove the `on hold` label and for future PRs that we don't want to merge, just tell the submitter to try again at a later stage, when the app has grown in userbase and has matured a little.

What do you guys think?

**Comment by capaldo** [comment]
I agree. That way we can start from 0. Furthermore, even if a cli app doesn't have votes maybe we can just decide amongst ourselves if its a well-mantained/widely used/unique/etc cli application.

**Comment by jneidel** [comment]
@sjclayton Are you on-board with this?

**Comment by capaldo** [comment]
I've already removed old PR's from 2017 and some from early 2018. I looked at most of the repo's and they dont have activity for several years now. Sorry for jumping the gun.

**Comment by jneidel** [comment]
@capaldo It's fine with me, I just wanted to get @sjclayton input, but he seems to be a little less active than before :smile:

**Comment by sjclayton** [comment]
@jneidel Sounds good to me!!
