### ISSUE TITLE
Check all apps for deprecation

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#330]
[I just removed](https://github.com/agarrharr/awesome-cli-apps/commit/07161b671874430ef2f53c062f27a509d58d5287) [bower-name-cli](https://github.com/sindresorhus/bower-name-cli), which was the first entry in web development, but has been deprecated for 6 months.

We might want to check all legacy cli and determine whether they are still:
- maintained
- relevant

**Comment by jneidel** [comment]
Script to check if github repo for any of the apps in the readme is archived:

```
APPS=$(cat readme.md | grep -e "- \[.\+\]\(.\+\)\s" | grep github | awk -F "(" '{ print $2 }' | cut -d ")" -f1)
for i in $(echo $APPS); do if [[ -n $(curl -SsL "$i" | grep "This repository has been archived by the owner. It is now read-only.") ]]; then echo DEPRECATED $i | tee >>out >(cat /dev/stdin); else echo CHECKED $i | tee >>out >(cat /dev/stdin); fi; done
```

**Comment by jneidel** [comment]
Or this version for parallel execution (100% cpu!):

```bash
APPS=$(cat readme.md | grep -e "- \[.\+\]\(.\+\)\s" | grep github | awk -F "(" '{ print $2 }' | cut -d ")" -f1)
for i in $(echo $APPS); do echo $(if [[ -n $(curl -SsL "$i" | grep "This repository has been archived by the owner. It is now read-only.") ]]; then echo DEPRECATED $i | tee >>out >(cat /dev/stdin); else echo CHECKED $i | cat /dev/stdin; fi) &; done
```

**Comment by itsyourOOP** [comment]
if it helps, rtv's not being maintained anymore. 

tuir's a fork of rtv that's still alive, but it's on gitlab

**Comment by jneidel** [comment]
> if it helps, rtv's not being maintained anymore.
> tuir is a fork of rtv that's still alive, but it's on gitlab

@itsyourOOP  Thanks for the notice! Do you want to open a PR replacing rtv with tuir? :smile:

**Comment by itsyourOOP** [comment]
sure

**Comment by itsyourOOP** [comment]
it's been put in
