### ISSUE TITLE
Organization?

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-cli-apps#334]
Since I almost never contribute this list anymore, perhaps we should move this repo to an organization on GitHub? But it may be overkill to move one repo that's just a list to an organization. We can leave it under my name, but I just wanted to let everyone know that I'm open to moving it.

**Comment by jneidel** [comment]
@agarrharr I think it's fine like this. Except for adding new maintainers we don't really need admin permissions :)
