### ISSUE TITLE
[Discussion] Active Maintainers?

### ISSUE THREAD

**Issue by jneidel** [agarrharr/awesome-cli-apps#340]
In the last two months only I committed to this project (which is fine by me).

But I wanted to check on all maintainers, see who is still active and who might want to get involved a little more (I can leave PRs open for you :smile:).

@sjclayton @capaldo @jamesgeorge007 @onehungrygeek @chrismullins @guangrei @HumanJBooF @paulrm @StewAlexanderACC

**Comment by HumanJBooF** [comment]
Hey I totally want to get involved more, been super busy the last few weeks but I can start checking on this a lot more now for sure.

**Comment by jneidel** [comment]
> I totally want to get involved more

@HumanJBooF good to know :)

I cleaned up the open PRs yesterday so all open issues/PRs are relevant now.

If you have ideas of your own on how to make this repo better feel free to open an discussion issue or implement it in a PR.

If new PRs come in feel free to self-assign them. If you have any questions you can always tag (@) me :smile:

**Comment by capaldo** [comment]
I just finished exams this past week so Ill be more active moving forward.

**Comment by jamesgeorge007** [comment]
:wave:

**Comment by jneidel** [comment]
Hey @jamesgeorge007,

Same for you:
> If you have ideas of your own on how to make this repo better feel free to open an discussion issue or implement it in a PR.

> If new PRs come in feel free to self-assign them. If you have any questions you can always tag (@) me :smile:

Just take initiative and I'll be there if you need help!

**Comment by StewAlexanderACC** [comment]
So cool to see all the feedback, thank you

**Comment by paulrm** [comment]
Great :+1:

**Comment by jneidel** [comment]
So in conclusion:

@HumanJBooF @capaldo @jamesgeorge007 @StewAlexanderACC @paulrm, you are all (semi-)active and want to take part in maintaining this repo.

I'll try to assign incoming PR to you guys. And if it's your first one point out what to look for :grin:
