### ISSUE TITLE
Inconsistent todo capitalization

### ISSUE THREAD

**Issue by capaldo** [agarrharr/awesome-cli-apps#353]
Under the [Note Taking and Lists](https://github.com/agarrharr/awesome-cli-apps/tree/kanban.bash#note-taking-and-lists) section of the README, the "todo" all have variable capitalization. Can we agree on what capitalization to use (TODO or todo) so that I can go ahead and create a PR to fix it.

**Comment by jneidel** [comment]
Makes sense, go ahead!
