### ISSUE TITLE
Typo in Readme Graphic

### ISSUE THREAD

**Issue by ashtron** [agarrharr/awesome-cli-apps#411]
The graphic at the top of the readme says "Entertaiment" instead of "Entertainment."

**Comment by jneidel** [comment]
How about:

![](https://user-images.githubusercontent.com/25589715/88457016-588e9b80-ce83-11ea-862a-bbba7e6aca98.png)

Edit at (bold & green text needs to be manually added): 
https://carbon.now.sh/?bg=rgba(255%2C255%2C255%2C1)&t=vscode&wt=none&l=auto&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Fira%20Code&fs=14.5px&lh=133%25&si=false&es=2x&wm=false&code=%250A%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520_%2520_%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250A%2520%2520__%2520___%2520%2520%2520%2520%2520%2520_____%2520%2520___%2520%2520___%2520%2520_%2520__%2520___%2520%2520%2520___%2520%2520%2520%2520___%257C%2520(_)%2520%2520%2520__%2520_%2520_%2520__%2520%2520_%2520__%2520%2520___%2520%250A%2520%252F%2520_%2560%2520%255C%2520%255C%2520%252F%255C%2520%252F%2520%252F%2520_%2520%255C%252F%2520__%257C%252F%2520_%2520%255C%257C%2520%27_%2520%2560%2520_%2520%255C%2520%252F%2520_%2520%255C%2520%2520%252F%2520__%257C%2520%257C%2520%257C%2520%2520%252F%2520_%2560%2520%257C%2520%27_%2520%255C%257C%2520%27_%2520%255C%252F%2520__%257C%250A%257C%2520(_%257C%2520%257C%255C%2520V%2520%2520V%2520%252F%2520%2520__%252F%255C__%2520%255C%2520(_)%2520%257C%2520%257C%2520%257C%2520%257C%2520%257C%2520%257C%2520%2520__%252F%2520%257C%2520(__%257C%2520%257C%2520%257C%2520%257C%2520(_%257C%2520%257C%2520%257C_)%2520%257C%2520%257C_)%2520%255C__%2520%255C%250A%2520%255C__%252C_%257C%2520%255C_%252F%255C_%252F%2520%255C___%257C%257C___%252F%255C___%252F%257C_%257C%2520%257C_%257C%2520%257C_%257C%255C___%257C%2520%2520%255C___%257C_%257C_%257C%2520%2520%255C__%252C_%257C%2520.__%252F%257C%2520.__%252F%257C___%252F%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%257C_%257C%2520%2520%2520%257C_%257C%2520%2520%2520%2520%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520Entertainment%2520-%2520Development%2520-%2520Productivity%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2526%2520much%2520more!%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250A

**Comment by ashtron** [comment]
Looks good to me!
