### ISSUE TITLE
Add SnowFS

### ISSUE THREAD

**Issue by seb-mtl** [agarrharr/awesome-cli-apps#446]
Hi!

Are new projects welcome? I would like to propose a new project called SnowFS, especially since the project is looking for more contributors. It is focusing on version control for binary files and is written in TypeScript. https://github.com/Snowtrack/SnowFS
Does this look interesting for this list?

Thanks!

**Comment by jneidel** [comment]
Sure, looks interesting.

Open a PR and add it under the [Version-Control](https://github.com/agarrharr/awesome-cli-apps#version-control) category.

**Comment by jneidel** [comment]
Actually, please wait out the 90 days [our contrib guide](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md) calls for.
Then feel free to open the PR, even if the app is still in alpha status.

**Comment by seb-mtl** [comment]
@jneidel Done! https://github.com/agarrharr/awesome-cli-apps/pull/459
