### ISSUE TITLE
Add vis

### ISSUE THREAD

**Issue by acidrums4** [agarrharr/awesome-cli-apps#489]
#### New App Submission

- [x] I've read the [contribution guidelines](https://github.com/agarrharr/awesome-cli-apps/blob/master/contributing.md#readme).

**Repo or homepage link:** https://github.com/martanne/vis

**Description:** A vi-like editor based on Plan 9's structural regular expressions

**Why I think it's awesome:** It combines the best of vim and sam editors, plus cool stuff like multiple cursors and rotations, while being small and fast enough to be used in embedded systems and for editing huge files.

**Comment by jneidel** [comment]
We only accept PRs. Feel free to reopen this as a PR submitting the app in the correct category.
