### ISSUE TITLE
Add Back To Top Button

### ISSUE THREAD

**Issue by alfiankan** [agarrharr/awesome-cli-apps#518]
I found myself jumping between sections inefficiently, maybe adding back to top button will be good
like https://github.com/avelino/awesome-go

<img width="907" alt="Screen Shot 2022-07-23 at 12 06 17" src="https://user-images.githubusercontent.com/40946917/180591313-bcb5fe38-6ee3-4aa1-8dc9-a5742e0b100b.png">

**Comment by jneidel** [comment]
You have access to the TOC over via the menu button at the top left of the readme.

<img width="896" alt="Screenshot 2022-07-25 at 11 17 58" src="https://user-images.githubusercontent.com/25589715/180742935-f07b738e-6a5c-4e5b-9f01-2ff0f0b5f559.png">

Personally I also have plugin (surfingkeys for vim bindings) which allows me to go to the top of the page.

Adding these will lead to inconsistencies as I even regularly forget to put stuff in the TOC when creating new sections, this would be another thing to keep track off.
