### ISSUE TITLE
Add IconicFonts

### ISSUE THREAD

**Issue by mdSlash** [agarrharr/awesome-cli-apps#628]
Hi there! I’ve created patched fonts with over 60,000 icons specifically for TUI projects. Can I submit a pull request to include [IconicFonts](https://github.com/iconicFonts/iconic-fonts) repository in awesome-cli-apps?

**Comment by jneidel** [comment]
Reminds me of [powerline](https://github.com/powerline/fonts) fonts.

Where would you include this?
Because it sounds a bit off-topic.

**Comment by mdSlash** [comment]
Sorry for suggesting that here - my bad.
