### ISSUE TITLE
Add stuff from ideas.txt

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-cli-apps#71]
I could use some help going through the [ideas.txt](https://github.com/aharris88/awesome-cli-apps/blob/5c57efe8ec7726872fe9aa89f165767df1aecc23/ideas.txt) file and adding these to the readme (if they are awesome). Also, be sure to remove the item from `ideas.txt` once you've moved it into the readme.

**Comment by oswalpalash** [comment]
Added some ones in PR : https://github.com/aharris88/awesome-cli-apps/pull/72

You could create an issue to list out more entries in ideas.txt? :dancing_men:

**Comment by aharris88** [comment]
Thanks! I would, but I actually just want to get rid of `ideas.txt`. I would rather have issues or pull requests for anything new.

**Comment by oswalpalash** [comment]
That makes sense too.

**Comment by jneidel** [comment]
Closed in favor of #267
